// <auto-generated />
using System;
using HealthwatcherApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthwatcherApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825113248_AddMonitorLease")]
    partial class AddMonitorLease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_targets");

                    b.ToTable("targets", (string)null);
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.TargetHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_target_history");

                    b.HasIndex("TargetId", "CheckedAt")
                        .HasDatabaseName("ix_target_history_target_id_checked_at");

                    b.ToTable("target_history", (string)null);
                });

            modelBuilder.Entity("HealthwatcherApi.Infrastructure.Monitoring.Leasing.MonitorLease", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<Guid>("Token")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_monitor_leases");

                    b.ToTable("monitor_leases", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiresAt = "0001-01-01T00:00:00.0000000Z",
                            Owner = "",
                            Token = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.Target", b =>
                {
                    b.OwnsOne("HealthwatcherApi.Shared.Common.HealthCheckRecord", "HealthCheckRecord", b1 =>
                        {
                            b1.Property<Guid>("TargetId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("Error")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("error");

                            b1.Property<double?>("ResponseTimeMs")
                                .HasColumnType("REAL")
                                .HasColumnName("response_time_ms");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status");

                            b1.Property<int?>("StatusCode")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status_code");

                            b1.HasKey("TargetId");

                            b1.ToTable("targets");

                            b1.WithOwner()
                                .HasForeignKey("TargetId")
                                .HasConstraintName("fk_targets_targets_id");
                        });

                    b.Navigation("HealthCheckRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.TargetHistory", b =>
                {
                    b.HasOne("HealthwatcherApi.Domain.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_target_history_targets_target_id");

                    b.OwnsOne("HealthwatcherApi.Shared.Common.HealthCheckRecord", "HealthCheckRecord", b1 =>
                        {
                            b1.Property<long>("TargetHistoryId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Error")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("error");

                            b1.Property<double?>("ResponseTimeMs")
                                .HasColumnType("REAL")
                                .HasColumnName("response_time_ms");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status");

                            b1.Property<int?>("StatusCode")
                                .HasColumnType("INTEGER")
                                .HasColumnName("status_code");

                            b1.HasKey("TargetHistoryId");

                            b1.ToTable("target_history");

                            b1.WithOwner()
                                .HasForeignKey("TargetHistoryId")
                                .HasConstraintName("fk_target_history_target_history_id");
                        });

                    b.Navigation("HealthCheckRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
