// <auto-generated />
using System;
using HealthwatcherApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthwatcherApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_targets");

                    b.ToTable("targets", (string)null);
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.TargetHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_target_history");

                    b.HasIndex("TargetId", "CheckedAt")
                        .HasDatabaseName("ix_target_history_target_id_checked_at");

                    b.ToTable("target_history", (string)null);
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.Target", b =>
                {
                    b.OwnsOne("HealthwatcherApi.Domain.Entities.HealthCheckRecord", "HealthCheckRecord", b1 =>
                        {
                            b1.Property<Guid>("TargetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Error")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("error");

                            b1.Property<double?>("ResponseTimeMs")
                                .HasColumnType("double precision")
                                .HasColumnName("response_time_ms");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<int?>("StatusCode")
                                .HasColumnType("integer")
                                .HasColumnName("status_code");

                            b1.HasKey("TargetId");

                            b1.ToTable("targets");

                            b1.WithOwner()
                                .HasForeignKey("TargetId")
                                .HasConstraintName("fk_targets_targets_id");
                        });

                    b.Navigation("HealthCheckRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthwatcherApi.Domain.Entities.TargetHistory", b =>
                {
                    b.HasOne("HealthwatcherApi.Domain.Entities.Target", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_target_history_targets_target_id");

                    b.OwnsOne("HealthwatcherApi.Domain.Entities.HealthCheckRecord", "HealthCheckRecord", b1 =>
                        {
                            b1.Property<long>("TargetHistoryId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Error")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("error");

                            b1.Property<double?>("ResponseTimeMs")
                                .HasColumnType("double precision")
                                .HasColumnName("response_time_ms");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<int?>("StatusCode")
                                .HasColumnType("integer")
                                .HasColumnName("status_code");

                            b1.HasKey("TargetHistoryId");

                            b1.ToTable("target_history");

                            b1.WithOwner()
                                .HasForeignKey("TargetHistoryId")
                                .HasConstraintName("fk_target_history_target_history_id");
                        });

                    b.Navigation("HealthCheckRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
